[package]
name = "ccsbl"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
strum = { version = "0.26.3", features = ["derive"] }
thiserror = "2.0.3"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
